# Generated by Django 6.0.3 on 2026-03-21 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('ktr', 'Transformation (.ktr)'), ('kjb', 'Job (.kjb)')], max_length=4)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Success'), ('error', 'Error')], default='ok', max_length=8)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Generation Log',
                'verbose_name_plural': 'Generation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
