# Generated by Django 6.0.3 on 2026-03-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('ktr', 'KTR'), ('kjb', 'KJB'), ('sql', 'SQL'), ('zip', 'ZIP')], max_length=10)),
                ('file', models.FileField(upload_to='generated_files/')),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='generator', max_length=50)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='transformer.generationlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
