# Generated by Django 6.0.3 on 2026-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0003_userapisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh', models.IntegerField(default=60)),
                ('toast', models.BooleanField(default=True)),
                ('auto_download', models.BooleanField(default=True)),
                ('debug', models.BooleanField(default=False)),
                ('history_limit', models.IntegerField(default=50)),
                ('folder_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
