# Generated by Django 6.0.3 on 2026-04-07 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('ktr', 'Transformation (.ktr)'), ('kjb', 'Job (.kjb)')], max_length=4)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Success'), ('error', 'Error')], default='ok', max_length=8)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Generation Log',
                'verbose_name_plural': 'Generation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh', models.IntegerField(default=60)),
                ('toast', models.BooleanField(default=True)),
                ('auto_download', models.BooleanField(default=True)),
                ('debug', models.BooleanField(default=False)),
                ('history_limit', models.IntegerField(default=50)),
                ('folder_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('ktr', 'KTR'), ('kjb', 'KJB'), ('sql', 'SQL'), ('zip', 'ZIP')], max_length=10)),
                ('file', models.FileField(upload_to='generated_files/')),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='generator', max_length=50)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='qlick_telend.generationlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(default='claude-opus-4-20250514', max_length=100)),
                ('max_tokens', models.IntegerField(default=16000)),
                ('timeout', models.IntegerField(default=180)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qlick_user_api_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
